DROP TABLE IF EXISTS orders;

CREATE TABLE orders (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    montantHT DECIMAL,
    tax_rate DECIMAL,
    montantTTC DECIMAL
);

CREATE OR REPLACE FUNCTION calculate()
  RETURNS TRIGGER
  AS
$$
BEGIN
    NEW.montantTTC := NEW.montantHT + (NEW.montantHT * NEW.tax_rate);
    RETURN NEW;
END;
$$
LANGUAGE plpgsql VOLATILE;


CREATE TRIGGER calculate_montant_ttc
    BEFORE INSERT
    ON orders
    FOR EACH ROW EXECUTE PROCEDURE calculate();


INSERT INTO orders (montantHT, tax_rate) VALUES (100, 0.2);
