DROP TABLE IF EXISTS auction, auction_logs;

CREATE TABLE auction(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    item VARCHAR(50) NOT NULL,
    bid DECIMAL(10, 2)  NOT NULL
);

CREATE TYPE actions AS ENUM ('create', 'update', 'delete');

CREATE TABLE auction_logs(
    id INTEGER,
    action actions,
    ts TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    item VARCHAR(50) NOT NULL,
    bid DECIMAL(10, 2)  NOT NULL
);

CREATE INDEX id_auction ON auction_logs(id);

CREATE RULE create_auction AS ON INSERT TO auction DO
    INSERT INTO auction_logs (action, id, ts, item, bid)
    VALUES ('create', NEW.id, current_timestamp, NEW.item, NEW.bid);

CREATE RULE update_auction AS ON UPDATE TO auction DO
    INSERT INTO auction_logs (action, id, ts, item, bid)
    VALUES ('update', NEW.id, current_timestamp, NEW.item, NEW.bid);

CREATE RULE delete_auction AS ON DELETE TO auction DO
    INSERT INTO auction_logs (action, id, ts, item, bid)
    VALUES ('delete', OLD.id, current_timestamp, OLD.item, OLD.bid);

INSERT INTO auction (item , bid) VALUES ('testing', 105.2356);
INSERT INTO auction (item , bid) VALUES ('sega', 458.12);
INSERT INTO auction (item , bid) VALUES ('nintendo', 1658.456);
INSERT INTO auction (item , bid) VALUES ('un bidule', 15647.1354);
UPDATE auction SET item = 'testing', bid = 108.845 WHERE id = 1;
UPDATE auction SET item = 'testing', bid = 109.845 WHERE id = 1;
UPDATE auction SET item = 'testing', bid = 110.86 WHERE id = 1;
UPDATE auction SET item = 'testing', bid = 1108.999 WHERE id = 1;
UPDATE auction SET item = 'testing', bid = 1201.35 WHERE id = 1;
DELETE FROM auction WHERE id = 1;